#! /bin/sh

sxhkd &


bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Google Chrome desktop='^2'
bspc rule -a Atom desktop='^1'
bspc rule -a Clion desktop='^1'
bspc rule -a Telegram desktop='^3'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

polybar bottom &
polybar top &
xwinwrap -ov -fs -- gifview -w WID -a $HOME/Downloads/output.gif &
compton &

